import type { NextPage } from "next";
import Head from "next/head";
import Border from "../components/Border";
import Motif from "../components/Motif";
import Title from "../components/Title";
import styles from "../styles/pages/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.wrap}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.fv}>
        <Border />
        <Title />
        <Border isBottom={true} />
      </section>
      <div className={styles.separator}>
        <Motif />
      </div>
    </div>
  );
};

export default Home;
