import type { NextPage } from "next";
import Head from "next/head";
import Title from "../components/Title";
import styles from "../styles/pages/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.wrap}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.fv}>
        <Title />
      </section>
    </div>
  );
};

export default Home;
