import type { NextPage } from "next";
import Head from "next/head";
import Border from "../components/Border";
import Layout from "../components/Layout";
import Motif from "../components/Motif";
import Title from "../components/Title";
import styles from "../styles/pages/Home.module.scss";

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.fv}>
        <Border />
        <Title />
        <Border isBottom={true} />
      </section>
      <div className={styles.separator}>
        <Motif />
      </div>
      <section className={styles.message}>
        <p className={styles.strong}>謹啓</p>
        <p>
          <span>皆様におかれましては</span>
          <span>ますますご清祥のこととお慶び申し上げます</span>
          <br />
          <span>このたび私たちは結婚をすることになりました</span>
          <br />
          <span>つきましては日頃お世話になっております皆様に</span>
          <span>感謝を込めてささやかな小宴を催したく存じます</span>
          <br />
          <span>ご多用中誠に恐縮ではございますが</span>
          <span>ぜひご出席をいただきたくご案内申し上げます</span>
        </p>
        <p className={styles.strong}>謹白</p>
      </section>
    </Layout>
  );
};

export default Home;
